name: rick_and_morty
description: Proyect using api of Rick And Morty in Rest.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.8.4
  http: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.5.0
  go_router: ^10.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/

